-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 03, 2017 at 11:34 PM
-- Server version: 10.1.21-MariaDB
-- PHP Version: 7.0.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `lokomet`
--

-- --------------------------------------------------------

--
-- Table structure for table `berita`
--

CREATE TABLE `berita` (
  `id_berita` int(5) NOT NULL,
  `id_kategori` int(5) NOT NULL,
  `username` varchar(50) NOT NULL,
  `judul` varchar(200) NOT NULL,
  `judul_seo` varchar(200) NOT NULL,
  `headline` enum('Y','N') NOT NULL,
  `isi_berita` text NOT NULL,
  `gambar` varchar(100) NOT NULL,
  `publish` enum('Y','N') NOT NULL,
  `hari` varchar(20) NOT NULL,
  `tanggal` date NOT NULL,
  `jam` time NOT NULL,
  `dibaca` int(5) NOT NULL DEFAULT '1',
  `tag` varchar(200) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `berita`
--

INSERT INTO `berita` (`id_berita`, `id_kategori`, `username`, `judul`, `judul_seo`, `headline`, `isi_berita`, `gambar`, `publish`, `hari`, `tanggal`, `jam`, `dibaca`, `tag`) VALUES
(22, 2, 'admin', 'Minion Ucapkan Bahasa Indonesia di Despicable Me 2', 'minion-ucapkan-bahasa-indonesia-di-despicable-me-2', 'Y', '<p>Menjelang rilis film animasi Despicable Me 2 lalu, sempat beredar kabar yang menarik perhatian penonton di Tanah Air, yakni sang sutradara Pierre Coffin ternyata anak dari NH Dini, salah satu novelis terkemuka Indonesia.</p>\r\n<p>Tidak hanya itu, Pierre Coffin ternyata juga memasukkan bahasa Indonesia dalam bahasa Minions yang merupakan karakter di dalam film tersebut. Hal itu diungkapkan Coffin dalam wawancara yang dilansir situs VOA Indonesia.</p>\r\n<p>\"Bahasa Indonesia menurut saya adalah bahasa yang sangat indah, seperti alunan musik. Ketika saya menyuarakan Minions dalam film Despicable Me, saya menggunakan berbagai bahasa. Setiap kata-kata lucu saya gunakan dengan cara menarik. Mungkin Anda mendengar saya menggunakan kata <strong>TERIMA KASIH</strong>,\" ujarnya.</p>\r\n<p>Ia mengatakan, bahasa Minions adalah campuran berbagai bahasa yang dia sukai, seperti Spanyol, Italia, Inggris, Indonesia, dan juga Yunani. Namun, yang lebih ditekankan adalah sonority atau resonansi suaranya sehingga tidak lugas.</p>\r\n<p>\"Bahasa Minions tidak bisa dimengerti, tapi diketahui dari bagaimana suaranya, proyeksinya, bagaimana membaca kalimatnya karena semua sudah saya tulis. Yang utama adalah penyampaiannya, bukan arti kata-katanya,\" ungkapnya (sumber: voaindonesia.com)</p>', '55minion.jpg', 'Y', 'Minggu', '2014-04-13', '14:54:20', 3, 'film'),
(11, 6, 'admin', 'CEO Malaysia Airlines Bersedia Mundur', 'ceo-malaysia-airlines-bersedia-mundur', 'Y', '<p>CEO Malaysia Airlines Ahmad Jauhari Yahya menyatakan bakal mempertimbangkan pengunduran dirinya sehubungan dengan insiden MH 370. Hal ini menanggapi banyaknya tuntutan dari berbagai pihak agar dia melepaskan jabatan di pucuk pimpinan maskapai tersebut.</p>\r\n<p>\"Akankah saya mundur? Hal itu adalah keputusan personal yang akan saya ambil nanti,&rdquo; ujarnya dalam konferensi pers, sebagaimana dikutip dari www.themalaymailonline.com Selasa (25/3/2014).</p>\r\n<p>Manajemen Malaysia Airlines berada di tengah sorotan terkait dengan kacaunya penanganan atas musibah MH 370 untuk rute Kuala Lumpur-Beijing. Di sisi lain, manajemen maskapai itu juga dianggap bersalah dalam memperlakukan para keluarga korban yang hilang dalam penerbangan tersebut.</p>', '98malaysian-airlines.jpg', 'Y', 'Kamis', '2014-03-27', '02:53:56', 12, 'malaysia-airlines'),
(12, 4, 'admin', 'Google Luncurkan Portal Pemilu Indonesia', 'google-luncurkan-portal-pemilu-indonesia', 'Y', '<p>Para pemilih di Indonesia kini bisa mengikuti berbagai berita dan tren terbaru seputar Pemilu di Google.co.id/pemilu, situs yang akan membantu 190 juta pemilih Indonesia, termasuk 67 juta pemilih pemula, untuk mendapatkan berita dan informasi terbaru dan membuat keputusan yang tepat pada Pemilu mendatang.<br /><br />Portal informasi Pemilu ini merupakan inisiatif pertama Google untuk mengumpulkan berbagai informasi yang tersedia secara online dengan tujuan agar para pemilih mendapatkan informasi mengenai kandidat dan proses pemilu secara lengkap.<br /><br />Google melakukan hal ini karena didorong oleh keinginan untuk meningkatkan keterlibatan pemilih Indonesia dalam pesta demokrasi. Bantuan teknologi memudahkan para pemilih mendapatkan berita dan informasi yang dibutuhkan.</p>\r\n<p>\"Peluncuran portal informasi Pemilu ini sejalan dengan misi Google untuk memberikan kemudahan mengakses informasi dan menjadikannya berguna secara universal. Kami berharap dengan peluncuran portal ini pemilih Indonesia akan memperoleh lebih banyak kemudahan untuk mendapatkan informasi yang dibutuhkan agar mereka bisa membuat pilihan yang tepat pada hari Pemilu,\" ujar Country Head Google Indonesia, Rudy Ramawy, dalam siaran pers, Rabu (26/3)</p>\r\n<p>Ditambahkan Rudy, hal tersebut merupakan bagian dari komitmen Google untuk mendigitalkan Indonesia dan menghubungkan pengguna Google dengan informasi penting yang bisa membuat hidup mereka lebih mudah.</p>\r\n<p>Portal informasi Pemilu ini menyediakan berbagai berita terkait Pemilu dengan menggunakan platform milik Google seperti halaman Google News yang didedikasikan untuk memuat berita Pemilu dari berbagai sumber berita di Indonesia; Google Trends untuk mengukur popularitas pencarian atas partai kandidat secara real-time; dan kanal YouTube yang akan menyiarkan berbagai pemberitaan dari kanal-kanal YouTube milik berbagai stasiun TV utama di Indonesia.</p>\r\n<p>Portal ini juga akan menyediakan tautan ke peta caleg interaktif yang dibuat oleh Perkumpulan untuk Pemilu dan Demokrasi (Perludem), organisasi nirlaba dengan fokus pada Pemilu Indonesia.</p>', '57google.jpg', 'Y', 'Kamis', '2014-03-27', '05:18:55', 18, 'pemilu-2014'),
(26, 1, 'admin', 'Bersyukur Raih Ballon dOr, Ronaldo Beri Hadiah Mobil untuk Fisioterapis', 'bersyukur-raih-ballon-dor-ronaldo-beri-hadiah-mobil-untuk-fisioterapis', 'Y', '<p>Cristiano Ronaldo memenuhi nazarnya jika berhasil meraih Ballon dOr 2013. Nazarnya itu adalah memberikan masing-masing sebuah mobil untuk empat fisioterapis Real Madrid. Selain itu, ia juga akan mengundang anak-anak penderita kanker.</p>\r\n<p>Dikutip dari Record, Cristiano Ronaldo menunaikan janjinya tersebut dua hari setelah menerima penganugerahan Ballon dOr. Hal itu tentunya disambut dengan sangat gembira oleh para fisioterapis tersebut. Selama ini, Ronaldo menilai jasa para terapis tersebut sangatlah besar hingga ia relatif terhndar dari cedera fatal selama gelaran musim 2013.</p>\r\n<p>Empat fisioterapis yang beruntung itu adalah Pedro Chueca , Dani Pirri , Javier Santamar&iacute;a, dan Juan Muro. Sebelumnya, CR7 berjanji kalaupun gagal merebut Ballon dOr, Ronaldo masih akan membelikan para tukang pijit Madrid mobil jika berhasil merebut gelar Liga Champions.</p>\r\n<p>Untuk para anak penderita kanker, Ronaldo mengatakan, \"Saya akan mengundang mereka untuk ikut pesta meriah jika saya memenangkan Golden dOr,\" ujarnya di Zurich sebelum penganugerahan gelar.</p>\r\n<p>Ronaldo dinobatkan sebagai pemain terbaik dunia 2013 dan berhak menerima trofi Bola Emas (Ballon dOr) untuk kedua kalinya. Kapten timnas Portugal itu mengalahkan dua pesaing kuat lainnya seperti Lionel Messi dan Franck Ribery.Trofi pertama diraihnya pada tahun 2008. Sejauh ini, pemain 28 tahun itu telah mengoleksi 230 gol dari 223 penampilannya di semua ajang bagi Los Blancos.</p>', '6ronaldo.jpg', 'Y', 'Kamis', '2014-04-17', '13:16:54', 1, 'sepakbola'),
(14, 1, 'admin', 'Lagu Resmi Piala Dunia 2014 Dapat Sentuhan Angklung', 'lagu-resmi-piala-dunia-2014-dapat-sentuhan-angklung', 'Y', '<p>Rakyat Indonesia sudah selayaknya bangga terhadap kebudayaan lokal. Pasalnya, alat musik tradisional, angklung, menjadi bagian dari lagu resmi Piala Dunia 2014, This World is Ours.</p>\r\n<p>Lagu persembahan partner resmi Piala Dunia 2014, Coca Cola, ini dibawakan oleh penyanyi jebolan X-Factor USA, David Correy. Pemuda berdarah Brasil ini berkolaborasi dengan grup perkusi asal Brasil, Monobloco.<br />Lagu ini diadaptasi ke dalam berbagai versi berbeda. Correy dan Monobloco juga berkolaborasi dengan budaya dan musisi lokal di berbagai negara, termasuk Indonesia.</p>\r\n<p>Dalam versi Indonesia, Correy dan Monobloco melibatkan penyanyi berdarah Jerman, Millane Fernandez. Selain Millane, pada lagu \"This World is Ours\" terdapat sentuhan bunyi angklung. Lagu ini juga disadur dalam bahasa Indonesia dengan judul \"Dunia Kita\".</p>', '19angklung.jpg', 'Y', 'Kamis', '2014-03-27', '13:39:14', 2, 'piala-dunia-2014'),
(27, 2, 'admin', 'The Amazing Spider-Man 2 Rilis Trailer Spektakuler', 'the-amazing-spiderman-2-rilis-trailer-spektakuler', 'Y', '<p>Sony Pictures akhirnya secara resmi merilis trailer final dari film The Amazing Spider-Man 2 yang sudah sangat dinantikan sejak lama. Trailer ini sepertinya akan memuaskan seluruh pecinta komik superhero manusia laba-laba ini.</p>\r\n<p>Jika film pertamanya lebih kental nuanasa drama sebagai perkenalan awal akan karakter Spider-Man, maka di film kedua ini sutradara Marc Webb memang sudah lebih banyak memberikan porsi untuk adegan action yang fantastis. Termasuk pertarungan epik Spider-Man melawan Electro dan Rhino di tengah kota New York di malam hari yang terlihat sangat spektakuler.</p>\r\n<p>Trailernya juga menampilkan untuk pertama kalinya sosok Hary Osborn yang di film versi terbaru Spidey ini diperankan oleh Aktror Dane DeHaan (menggantikan James Franco di versi sebelumnya).</p>\r\n<p>Bagi yang sudah penasaran, silahkan saksikan trailernya dulu berikut ini:</p>\r\n<p><iframe src=\"http://www.youtube.com/embed/SO0r3JrnATk?wmode=transparent\" frameborder=\"0\" width=\"600\" height=\"350\"></iframe></p>', '15spiderman.jpg', 'Y', 'Jumat', '2014-04-18', '11:27:46', 15, 'film'),
(16, 2, 'admin', 'Captain America The Winter Soldier Banjir Pujian Film Superhero Terbaik', 'captain-america-the-winter-soldier-banjir-pujian-film-superhero-terbaik', 'Y', '<p>Film sekuel Superhero &ldquo;Captain America: The Winter Soldier&rdquo; yang baru saja diputar perdana semalam di hadapan para wartawan di Los Angeles ternyata mendapatkan respon yang luar biasa positif.</p>\r\n<p>Walaupun pihak Marvel telah meng-embargo para wartawan untuk tidak menulis ulasan film ini sampai tanggal 20 Maret 2014, namun komentar dari para wartawan yang hadir tetap saja &lsquo;bocor&rsquo; terlebih dulu lewat Twitter.</p>\r\n<p>Para kritikus terkenal seperti Jeremy Smith menyebut film kedua Captain America ini lebih baik dari semua film yang pernah diproduksi oleh Marvel Studios. Pendapat serupa juga diungkapkan oleh PJ Campbell.</p>\r\n<p>Sementara&nbsp; Matt Blum yang menyebut filmnya sebagai &ldquo;Film action terbaik yang pernah aku tonton seumur hidupku&rdquo;.</p>\r\n<p>Semakin tidak sabar ingin segera menyaksikan filmnya, bukan? Captain America: The Winter Soldier direncanakan akan tayang di bioskop-bioskop Amerika (dan Indonesia) serempak mulai 4 April 2014.</p>\r\n<p>Captain America: The Winter Soldier akan bersetting setelah kejadian pertempuran besar di New York (di film The Avengers). Steve Rogers/Captain America kini telah hidup tenang di Washington DC. Namun saat menerima kabar bahwa rekannya di S.H.I.E.L.D. diserang, Steve memutuskan untuk kembali beraksi dan bergabung bersama Black Widow (Scarlett Johansson). Setelah menyelamatkan sekutu mereka &ldquo;Falcon&ldquo; (Anthony Mackie), mereka berdua kemudian harus menghadapi musuh baru yang sangat kuat dan tak pernah mereka duga sebelumnya&hellip;. the Winter Soldier (Sebastian Stan).</p>\r\n<p>Filmnya dibintangi oleh Chris Evans, Scarlett Johansson, Cobie Smulders, Georges St-Pierre, Frank Grillo, Hayley Atwell, Toby Jones, Emily VanCamp, Maximiliano Hern&aacute;ndez, Robert Redford, dan Samuel L. Jackson.</p>\r\n<p><iframe src=\"http://www.youtube.com/embed/7SlILk2WMTI?wmode=transparent\" frameborder=\"0\" width=\"600\" height=\"350\"></iframe></p>', '98black-widow.jpg', 'Y', 'Senin', '2014-03-31', '03:08:34', 8, 'film'),
(17, 2, 'admin', 'Film Frozen Tembus Rekor Box Office 12 Trilyun Rupiah', 'film-frozen-tembus-rekor-box-office-12-trilyun-rupiah', 'Y', '<p>Tak salah mungkin jika film Frozen disebut sebagai film animasi tersukses dan juga paling beruntung sepanjang tahun 2013-2014.&nbsp;</p>\r\n<p>Tak hanya sukses secara finansial di box office, film produksi Disney ini juga sukses di berbagai ajang penghargaan film. Termasuk piala tertinggi &ldquo;film animasi terbaik&rdquo; Oscars 2014 yang baru saja diterimanya kemarin (3/3).</p>\r\n<p>Melengkapi prestasi piala Oscar nya, Frozen juga baru saja memecahkan rekor box office dengan penghasilan yang telah melebihi $1 Milyar (sekitar 12 Trilyun Rupiah).</p>\r\n<p>Dari peanyangannya di Amerika sejak tanggal 22 November 2013 lalu, Frozen telah meraup untung $388.7 Juta. Sedangkan dari penayangannya di negara-negara lain (termasuk bioskop Indonesia tentunya), film yang diisi suaranya oleh Kristen Bell ini menghasilkan $611.5 Juta.</p>\r\n<p>Penghasilan ini sekaligus membawa &lsquo;Frozen&lsquo; menempati posisi ke-18 film terlaris sepanjang sejarah, dibawah posisi &ldquo;The Dark Knight&ldquo;.</p>\r\n<p>Sebagai film rilisan 2013, Frozen menjadi film terlaris kedua tahun lalu setelah Iron Man 3 yang juga diproduksi oleh Disney.</p>\r\n<p>Anda yang belum sempat menyaksikan filmnya di bioskop, bisa segera menyaksikannya di rumah melalui DVD dan BluRay nya yang akan dirilis mulai tanggal 18 Maret 2014 mendatang. (sumber: sidomi.com)</p>', '94frozen.jpg', 'Y', 'Senin', '2014-03-31', '16:06:39', 4, 'film'),
(18, 7, 'admin', 'Manfaat Lari Pagi yang Menakjubkan', 'manfaat-lari-pagi-yang-menakjubkan', 'N', '<p>Lari pagi merupakan olah raga yang sangat menyehatkan tubuh kita. Bukan hanya badan menjadi lebih sehat namun sistem pernafasan juga akan menjadi lebih bersih karena udara yang kita hirup merupakan udara pagi yang masih bersih dan belum banyak mengandung polusi. Manfaat lari pagi setiap hari dapat meningkatkan kinerja jantung, paru-paru dan tulang, tetapi ada juga beberapa kekurangan yang ditimbulkan.</p>\r\n<p>Jogging selama setidaknya satu jam per minggu dapat menambahkan beberapa tahun untuk masa hidup Anda. Sebuah penelitian baru-baru ini mempresentasikan data yang mengungkapkan lari pagi secara teratur dapat meningkatkan harapan hidup lima hingga enam tahun pada pria dan wanita . Spesialis jantung Dr Peter Schnohr dan rekan-rekannya menyimpulkan bahwa antara satu dan dua setengah jam seminggu lari pagi intens cukup ideal untuk umur panjang.</p>\r\n<p>The American Diabetes Association menerbitkan sebuah studi pada tahun 2011 yang menyatakan penurunan berat badan dari 5 persen menjadi 10 persen dapat mengurangi risiko penyakit kardiovaskular. Manfaat lari pagi meliputi pemeliharaan berat badan dan peningkatan fungsi jantung.</p>\r\n<p>Tidak hanya lari pagi meningkatkan daya tahan, tetapi juga membantu Anda mempertahankan dan membangun ketebalan tulang Anda. Lari pagi juga memiliki dampak positif pada tulang belakang , pinggul dan otot di moderasi. Bagi orang dewasa, mereka akan mengalami masalah jantung jika melakukan lari pagi melebihi ambang batas yang ditentukan untuk itu batasi sesi lari pagi 30 menit sehari, tiga kali seminggu agar manfaat jogging bisa maksimal.</p>', '24laripagi.jpg', 'Y', 'Selasa', '2014-04-01', '01:14:43', 1, ''),
(19, 3, 'admin', 'Fatwa MUI Soal Golput Haram Terlalu Keras', 'fatwa-mui-soal-golput-haram-terlalu-keras', 'N', '<p>Majelis Ulama Indonesia (MUI) mengeluarkan fatwa haram terhadap masyarakat yang tidak menggunakan hak suaranya atau golput pada saat pemilu. Ketua Dewan Kehormatan Penyelenggaran Pemilu (DKPP) Jimly Asshiddiqie menilai, fatwa MUI itu terlalu keras bagi masyarakat.&nbsp;</p>\r\n<p>&ldquo;Saya rasa tidak perlu sampai fatwa. Kalau dijadikan fatwa syar&rsquo;i itu terlalu keras,&rdquo; kata Jimly usai menghadiri kegiatan Tabligh Akbar Pengajian Politik Islam (TAPI) di Masjid Agung Al-Azhar, Jakarta, Minggu (30/3/2014).&nbsp;</p>\r\n<p>Kendati demikian, Jimly mengapresiasi upaya MUI dalam membantu Komisi Pemilihan Umum untuk meminimalisir tingkat golput di masyarakat. Secara moral, menurutnya, semua pihak seharusnya memberikan dukungan kepada MUI.&nbsp;</p>\r\n<p>&ldquo;Secara moral itu bagus, niat baiknya (MUI) harus kita hargai,&rdquo; ujarnya.&nbsp;</p>\r\n<p>Diberitakan Tribunnews.com sebelumnya, fatwa haram golput yang dikeluarkan MUI ini merupakan salah satu bentuk upaya dari para ulama untuk menegakkan demokrasi di Indonesia.</p>\r\n<p>Ketua Komisi Fatwa MUI Jawa Barat, Salim Umar mengatakan bahwa di antara para calon pemimpin, ada yang memenuhi syarat. Maka itu, umat Islam wajib hukumnya untuk menggunakan hak pilihnya.&nbsp;</p>\r\n<p>&ldquo;Jadi itu nomor satu harus memilih yang memenuhi syarat. Kedua, kalau dalam calon-calon itu ada yang memenuhi syarat, maka umat Islam wajib memilih dan haram hukumnya golput. Haram hukumnya tidak memilih, kalau memang di antara calon-calon itu memenuhi syarat,&rdquo; kata Salim Umar.&nbsp;</p>\r\n<p>Fatwa haram golput dikeluarkan oleh MUI pada saat Ijtima Ulama di Kota Padang Panjang, Sumatera Barat, tahun 2009 lalu. Untuk mensosialisasikan fatwa haram ini, MUI menggerakkan para da&rsquo;i atau juru dakwah untuk menyebarkan informasi fatwa tersebut kepada seluruh masyarakat muslim. MUI menjadi sumber konsultasi para da&rsquo;i untuk melakukan tugas sosialisasi penyebaran informasi fatwa haram golput.</p>', '62golputx.jpg', 'Y', 'Selasa', '2014-04-01', '01:38:06', 28, 'pemilu-2014'),
(20, 3, 'admin', 'Game Pemilu 2014, Game Ajang Sosialisasi Pemilu 2014', 'game-pemilu-2014-game-ajang-sosialisasi-pemilu-2014', 'Y', '<p>Game Pemilu 2014 bukan hanya sekadar permainan. Game ini juga berposisi sebagai alat sosialisasi Pemilu. Dalam hitungan pekan, negara ini akan menggelar hajatan pesta demokrasi 5 tahunan. Apakah Anda sudah siap untuk itu?</p>\r\n<p>Siap bukan hanya berarti sekadar ready untuk nyoblos. Apakah Anda telah mengenal calon partai terpilih yang bakal dicoblos? Apakah Anda telah miliki dambaan sosok yang bakal diusung jadi calon presiden?</p>\r\n<p>Game ini berikan informasinya. Anda bisa mengenal pelbagai partai dan sejumlah informasi terkait beserta profil capres yang diusung. Karena tak kenal maka tak sayang, maka mau tidak mau Anda wajib mengenal siapa-siapa yang bakal jadi calon pemimpin bangsa dalam lima tahun ke depan.</p>\r\n<p>Di diskripsi Google Play, Game Pemilu Menyebut jika di era saat ini bentuk kampanye tak perlu beramai-ramai di ruang terbuka atau membentu orasi dengan kumpulkan ribuan massa. Melalui sebuh ruang pribadi di perangkat bergerak, kampanye juga bisa dilakukan (sumber: sidomi.com).</p>', '81game-pemilu.jpg', 'Y', 'Selasa', '2014-04-01', '04:03:38', 1, 'pemilu-2014'),
(21, 3, 'admin', 'Teori Goodfellow Soal Sebab Jatuhnya MH370 ', 'teori-goodfellow-soal-sebab-jatuhnya-mh370-', 'N', '<p>Chris Goodfellow, pilot Kanada yang telah berpengalaman selama 20 tahun, memiliki teori sebab jatuhnya Boeing 777 Malaysia Airlines. Seperti yang dilansir situs BBC, 19 Maret 2014, Goodfellow telah menduga pesawat MH370 mencoba mendarat di Langkawi dan akhirnya jatuh ke selatan Samudra Hindia.</p>\r\n<p>\"Saya bisa mengetahui hal itu ketika melihat aplikasi Google Earth. Dalam waktu 30 detik, saya menemukan Langkawi,\" ujar Goodfellow. \"Setiap pilot berpengalaman pasti telah hafal di luar kepala akan letak bandara terdekat dari posisi pesawatnya.\"</p>\r\n<p>Dalam teori Goodfellow, MH370 mengalami kebakaran di ruang kokpit. Api itu bisa dimunculkan oleh aliran singkat listrik atau ban yang panas setelah pesawat tinggal landas. Menghadapi krisis, awak pesawat diduga memutuskan berbelok ke Langkawi. Sedangkan pilot memutuskan sirkuit, seperti transponder, sebagai usaha menghentikan sambaran api.</p>\r\n<p>\"Namun semua usaha tidak berguna karena awak dan penumpang pesawat telah terkepung asap,\" ujar Goodfellow. \"Pesawat pun terbang dengan sistem autopilot, kemudian jatuh di Samudra Hindia Selatan setelah kehabisan bahan bakar.\"</p>\r\n<p>Menurut Goodfellow, pilot Zaharie Ahmad Shah merupakan pahlawan dalam penerbangan MH370. Sebab, ia telah berjuang untuk menyelamatkan awak serta penumpang pesawat nahas itu. \"Dia pilot yang cerdas, sayang tidak memiliki cukup banyak waktu.\"</p>\r\n<p>Prediksi Goodfellow tentang letak jatuhnya MH370 memang tidak salah. Namun teorinya soal kebakaran dalam pesawat ditentang oleh Greg Feith, mantan penyelidik kecelakaan National Transportation Safety Board. Menurut Feith, biasanya asap akan terlebih dulu tercium sebelum api berkobar. Pada saat itu, pilot dapat mengenakan masker oksigen. \"Jika sistem pesawat masih berfungsi, pilot pun bisa mengirimkan sinyal mayday,\" ujar Feith. (sumber: tempo.co).</p>', '19mh370.jpg', 'Y', 'Selasa', '2014-04-01', '04:30:01', 1, 'malaysia-airlines'),
(8, 1, 'admin', 'Messi Jadi Brand Ambassador WeChat', 'messi-jadi-brand-ambassador-wechat', 'Y', '<p>Lionel Messi terpilih sebagai brand ambassador aplikasi chatting WeChat. Karena itu, wajah Messi akan muncul di TVC atau iklan WeChat di layar kaca.&nbsp; Iklan tersebut menunjukkan Messi yang mengenakan jaket hijau berada di dapur rumahnya dan berinteraksi dengan layanan chatting sebelum berangkat berlatih.</p>\r\n<p>Menurut David Audy selaku chief executive MNC Tencent, bintang Barcelona ini dipilih karena WeChat menginginkan sosok terbaik sebagai representatif produk asal China tersebut. Hal ini tak lepas dari posisi WeChat sebagai aplikasi chatting yang tengah berkembang pesat.&nbsp;</p>\r\n<p>\"Kami memakai Messi karena dia sosok pemain sepak bola terbaik. Sebagai aplikasi terbaik, tentu memilih bintangnya harus yang terbaik,\" jelas David dalam media gathering di Pisa Cafe, Menteng, Rabu (10/7/2013).&nbsp;</p>\r\n<p>Ucapan David ini tentu mengacu ke prestasi Messi sebagai peraih Ballon dOr selama empat tahun berturut-turut. Adapun pengguna WeChat di sejumlah negara telah mencapai 300 juta pengguna, dengan 70 juta di antaranya berasal dari China.&nbsp;</p>\r\n<p>Kemunculan sosok Messi sebagai brand ambassador WeChat pun dapat dirasakan pengguna aplikasi ini melalui akun MessiOfficial. Dengan mengikuti akun resmi ini, pengguna WeChat dapat mendapatkan video, pesan suara dan foto eksklusif.</p>', '87messi.jpg', 'Y', 'Selasa', '2014-04-01', '04:39:59', 31, 'sepakbola'),
(23, 3, 'admin', 'Saling Serang Capres di Ranah Maya Kian Sengit', 'saling-serang-capres-di-ranah-maya-kian-sengit', 'N', '<p>Pendiri Politicawave Yose Rizal mengatakan saling serang antarpendukung partai dan calon presiden akan makin sengat di jagat maya. Serangan-serangan itu disebut sudah berlangsung sejak beberapa pekan sebelum pemilu legislatif pada 9 April mendatang.</p>\r\n<p>\"Tapi serangan-serangan itu tak resmi dari akun partai,\" kata Yose saat dihubungi, Selasa, 1 April 2014. Kendati tak resmi, kata Yose, serangan dari akun-akun perorangan tersebut bisa dilacak arah hubungannya dengan partai-partai atau calon presiden tertentu. Salah satunya, kata Yose, adalah serangan Wakil Sekretaris Jenderal Partai Keadilan Sejahtera Fachri Hamzah terhadap Partai Demokrasi Indonesia Perjuangan dan Megawati Soekarnoputri beberapa waktu lalu.&nbsp;</p>\r\n<p>\"Itu kemudian diamplifikasi oleh banyak akun, baik relawan atau yang berafiliasi dengan mereka,\" kata Yose.&nbsp; Yose memprediksi serangan-serangan politik yang dialamatkan ke calon presiden atau partai tertentu akan makin gencar jelang sepekan pemilihan legislatif. Sebab, sosial media belum diatur penggunaannya dalam kampanye oleh Komisi Pemilihan Umum.</p>\r\n<p>\"Nah, yang diserang harus rajin menyediakan counter informasinya. Sebab, kalau serangan itu dibiarkan, netizen lama-lama menganggap serangan itu sebagai fakta. Padahal, belum tentu itu benar,\" kata Yose.</p>\r\n<p>Yose mengakui jagat maya memang belum banyak digunakan oleh partai-partai atau salah satu calon presiden untuk menginformasikan diri mereka. Praktis, kata Yose, hanya PKS yang cukup fasih menggunakan sosial media.&nbsp;</p>\r\n<p>Adapun PDIP, justru lebih aktif lewat relawan-relawan dan orang-orang yang terafiliasi dengan mereka. Gerindra, kata Yose, kendati rajin bermain di jagat maya, tapi serangan mereka lebih banyak terjadi di ranah offline. Sedangkan partai-partai lain seperti Golkar dan Demokrat cenderung keteteran di sosial media (sumber: tempo.co).</p>', '17dunia-maya.jpg', 'Y', 'Selasa', '2014-04-01', '05:03:05', 2, 'pemilu-2014'),
(24, 1, 'admin', 'Grup-Grup Neraka di Piala Dunia 2014', 'grupgrup-neraka-di-piala-dunia-2014', 'N', '<p>Undian grup Piala Dunia Brasil yang dihelat di kota Bahia, Salvador, Brasil Jumat (6/12) waktu setempat menghasilkan dua grup neraka yang akan saling mempertemukan antara tim kuat dari benua Eropa dan Amerika Selatan.</p>\r\n<p>Pertama adalah reuni duo finalis Piala Dunia 2010 yang tergabung dalam grup B. Juara bertahan Spanyol akan lebih dini menghadapi tim kuat Belanda disusul Chile dan Australia juga tergabung dalam grup ini.</p>\r\n<p>Grup neraka kedua berada di Grup D dimana tim kuat Uruguay akan menghadapi dua negara bertabur pemain bintang yakni Inggris dan Italia. Uruguay yang diperkuat Luis Suarez dan Edinson Cavani harus mempersiapkan diri menghadapi Rooney dan Gerrard dari Inggris maupun menghadapi Balotelli dan De Rossi dari Italia.</p>\r\n<p>Kosta Rika yang tergabung bersama Uruguay, Inggris dan Italia dalam grup D ini bisa dibilang menjadi negara paling sial karena harus menghadapi tiga negara kuat tersebut. Disisi lain akan sangat menarik melihat Inggris yang merupakan negara dengan liga terbaik di dunia harus berjuang di grup neraka ini.</p>\r\n<p>Selain itu pemain paling bersinar tahun ini, Cristiano Ronaldo harus berjuang bersama Portugal di grup G untuk bersaing dengan Jerman, Amerika Serikat dan Unggulan dari benua Afrika, Ghana. Akan menjadi menarik dalam grup ini ketika pelatih Amerika Serikat yang juga mantan bintang Jerman di era 90-an, Jurgen Klinsman, harus menghadapi tanah kelahirannya.</p>\r\n<p>Argentina bisa dibilang menjadi negara unggulan paling beruntung pada pembagian grup ini. Hal itu beralasan karena di Grup F Argentina dipertemukan dengan Nigeria, Iran sebagai wakil dari Asia dan negara yang baru pertama kalinya mengikuti Piala Dunia yaitu Bosnia Herzegovina.</p>\r\n<p>Selain itu Perancis yang lolos ke putaran final Piala Dunia 2014 dengan susah payah harus menerima tidak menjadi negara unggulan dan berada satu grup bersama Swiss dan dua negara kuda hitam dari benua Amerika yang bisa saja menjegal langkah mereka yakni Ekuador dan Honduras.</p>\r\n<p>Tuan rumah Brasil yang tergabung di grup A bersama Meksiko, Kamerun dan Kroasia jika lolos ke fase berikutnya maka akan bertemu dengan wakil dari grup B yang dihuni oleh Spanyol, Belanda dan Chile.</p>\r\n<p>Pertandingan pembuka Piala Dunia 2014 akan dihelat di Sao Paulo pada 12 Juni 2014. Kejuaraan empat tahun sekali ini menurut rencana akan dihelat di 12 lokasi di Brasil yakni Belo Horizonte, Brasilia, Cuiaba, Curitiba, Fortaleza, Manaus, Natal, Porto Alegre, Recife,&nbsp; Rio de Janeiro, Salvador and Sao Paulo (sumber: antaranews.com)</p>', '72bola-brazuca.jpg', 'Y', 'Selasa', '2014-04-01', '08:24:01', 4, 'piala-dunia-2014'),
(25, 1, 'admin', 'Kagetnya Millane Fernandez Terpilih Nyanyikan Lagu World Cup 2014', 'kagetnya-millane-fernandez-terpilih-nyanyikan-lagu-world-cup-2014', 'N', '<p>Millane Fernandez tak pernah membayangkan untuk go international dalam karier bernyanyinya. Ia hanya melakukan yang terbaik dalam setiap menuangkan karya-karyanya.</p>\r\n<p>Tidak disangka-sangka, adik kandung Nino Fernandez itu, kemudian terpilih untuk menyanyikan Fifa World Cup 2014 song anthem berjudul \"The World Is Ours\", yang ditulis oleh Rock Mafia. Seperti diketahui, Rock Mafia dikenal sebagai penulis lagu untuk sejumlah penyanyi beken dunia, diantaranya Justin Bieber dan Miley Cyrus.</p>\r\n<p>\"Kadang orang pikir, kita harus go international, harus keluar (negeri), enggak juga. Kaya pengalaman aku, seperti musisi kita, desainer kita, they are all out saja berikan yang terbaik,\" ucapnya, saat ditemui di kawasan Epicentrum, Kuningan, Jakarta.</p>\r\n<p>Millane sendiri jadi buktinya. Selama enam bulan terakhir, aktivitasnya sebagai penyanyi dipantau. Tentu ia tak sendirian. Ada 70 penyanyi yang juga turut diseleksi untuk nyanyikan Fifa World Cup 2014 song anthem. Ia kemudian terpilih menyanyikannya bersama David Correy dan Monobloco.</p>\r\n<p>\"Dan akhirnya mereka memilih aku. Dan aku yang, \"Hah gua?! Gua mana mungkin,\" ucapnya. Baginya, kesempatan menyanyikan song anthem tersebut, seperti mimpi.</p>\r\n<p>\"Kaya mimpi saja bisa dipercaya untuk bawakan World Cup song anthem, sekalian merepresentasikan Indonesia. Itu rasanya luar biasa banget dan beban yang luar biasa juga. Sekali lagi ini suatu yang berat,\" lanjutnya.</p>\r\n<p>Namun, ia tak lantas jiper. Baginya, untuk mencapai hasil yang maksimal harus mengeluarkan segenap potensinya. \"Aku harus mendorong diri aku sendiri sampai limit,\" tandasnya (sumber: tribunnews.com).</p>', '70millane-fernandez.jpg', 'Y', 'Selasa', '2014-04-01', '10:03:02', 2, 'piala-dunia-2014'),
(10, 1, 'admin', 'Piala Dunia 2014 Bakal Berbeda', 'piala-dunia-2014-bakal-berbeda', 'Y', '<p>Legenda sepak bola Brasil, Pele, optimistis tim Samba mampu meraih gelar juara Piala Dunia 2014. Pria berusia 73 tahun merasa yakin Brasil akan meraih gelar juara Piala Dunia saat bertindak sebagai tuan rumah.</p>\r\n<p>Brasil sudah pernah menggelar Piala Dunia pada 1950. Sayang, di kesempatan itu mereka tak mampu meraih gelar juara untuk pertama kali. Uruguay menghadirkan mimpi buruk bagi Brasil di partai final.</p>\r\n<p>\"Kami mempunyai pengalaman buruk pada 1950 ketika berlaga di Piala Dunia. Brasil menderita kekalahan dari Uruguay. Sekarang, orang-orang khawatir sesuatu yang sama akan terjadi. Tetapi, saya berpikir ini akan berbeda,\" ujar Pele seperti dilansir situs AFP.</p>\r\n<p>Setelah kegagalan meraih gelar juara di Piala Dunia 1950, sepak bola Brasil kembali bangkit. Mereka mampu meraih lima kali gelar juara sepanjang gelaran turnamen yang sudah berlangsung sejak 1930.<br />Pele merupakan pemain yang membawa Brasil meraih tiga kali gelar juara Piala Dunia, yakni pada 1958, 1962, dan 1970. Kemudian, mendapatkan trofi tersebut pada 1994 dan 2002 (sumber: tribunnews.com).</p>', '98pialadunia.jpg', 'Y', 'Selasa', '2014-04-01', '10:13:20', 41, 'piala-dunia-2014'),
(9, 1, 'admin', 'Neymar, Andalan Brasil Rebut Juara Piala Dunia 2014', 'neymar-andalan-brasil-rebut-juara-piala-dunia-2014', 'N', '<p>Legenda sepak bola Brasil, Pele, mengandalkan Neymar untuk meraih gelar juara Piala Dunia 2014.<br />Tim Samba mempunyai kenangan pahit saat menjadi tuan rumah Piala Dunia. Pada 1950, Brasil gagal meraih gelar juara, setelah takluk dari Uruguay di partai final.</p>\r\n<p>Pele masih berusia 9 tahun ketika itu. Namun, berselang 8 tahun kemudian, dia membawa Brasil meriah gelar juara Piala Dunia untuk pertama kali.</p>\r\n<p>Kemudian, Pele melanjutkannya pada tahun 1962 dan 1970. Brasil tercatat sudah lima kali meraih gelar juara. Dua gelar selanjutnya diraih pada 1994 dan 2002.</p>\r\n<p>&ldquo;Saya berpikir tekanan yang anda berbicara tentang ada, \"tapi bahwa\" dia akan pergi ke Brasil setelah mendapatkan pengalaman \"dengan Barcelona,&rdquo; kata Pele seperti dilansir AP (sumber: tribunnews.com)</p>', '19neymar.jpg', 'Y', 'Selasa', '2014-04-01', '10:17:18', 2, 'piala-dunia-2014');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `berita`
--
ALTER TABLE `berita`
  ADD PRIMARY KEY (`id_berita`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `berita`
--
ALTER TABLE `berita`
  MODIFY `id_berita` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=29;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
